import { Inter } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";
import { ReactQueryProvider } from "./ReactQueryProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wordify",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">

      <ReactQueryProvider>
        <AuthContext>
          <body className={inter.className}>
            {children}
          </body>
        </AuthContext>
      </ReactQueryProvider>

    </html>
  );
}
